#!/usr/bin/env python3
"""Generate seed SQL for the optional Supabase fullstack skeleton."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
USERS_PATH = ROOT / "datasets" / "demo_acl" / "users.json"
CHUNKS_PATH = ROOT / "datasets" / "demo_documents" / "chunks.jsonl"


def sql_text(value: Any) -> str:
    if value is None:
        return "null"
    return "'" + str(value).replace("'", "''") + "'"


def sql_bool(value: bool) -> str:
    return "true" if value else "false"


def sql_int(value: Any) -> str:
    if value is None:
        return "null"
    return str(int(value))


def sql_timestamptz(value: Any) -> str:
    if value is None:
        return "null"
    return f"{sql_text(value)}::timestamptz"


def load_jsonl(path: Path) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    with path.open("r", encoding="utf-8") as handle:
        for line in handle:
            if line.strip():
                rows.append(json.loads(line))
    return rows


def write_statement(handle, statement: str) -> None:
    handle.write(statement.rstrip())
    handle.write("\n")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--users", type=Path, default=USERS_PATH)
    parser.add_argument("--chunks", type=Path, default=CHUNKS_PATH)
    parser.add_argument("--output", type=Path, default=None)
    args = parser.parse_args()

    users = json.loads(args.users.read_text(encoding="utf-8"))
    chunks = load_jsonl(args.chunks)

    tenant_ids = sorted({user["tenant_id"] for user in users} | {chunk["tenant_id"] for chunk in chunks})
    groups = sorted(
        {
            (user["tenant_id"], group)
            for user in users
            for group in user.get("groups", [])
        }
        | {
            (chunk["tenant_id"], group)
            for chunk in chunks
            for group in chunk.get("allowed_groups", [])
        }
    )

    documents: dict[str, dict[str, Any]] = {}
    document_groups: set[tuple[str, str, str]] = set()
    for chunk in chunks:
        documents.setdefault(
            chunk["document_id"],
            {
                "document_id": chunk["document_id"],
                "tenant_id": chunk["tenant_id"],
                "title": chunk["title"],
                "department": chunk["department"],
                "project_id": chunk["project_id"],
                "document_type": chunk["document_type"],
                "document_version": chunk.get("document_version"),
                "updated_at": chunk.get("updated_at"),
            },
        )
        for group in chunk.get("allowed_groups", []):
            document_groups.add((chunk["document_id"], chunk["tenant_id"], group))

    output = args.output.open("w", encoding="utf-8") if args.output else None
    handle = output if output else __import__("sys").stdout

    try:
      write_statement(handle, "-- Generated by scripts/export_supabase_seed.py")
      write_statement(handle, "-- Apply supabase/schema.sql first. Do not add service_role keys here.")
      write_statement(handle, "begin;")

      for tenant_id in tenant_ids:
          write_statement(
              handle,
              "insert into public.tenants (id, name) "
              f"values ({sql_text(tenant_id)}, {sql_text(tenant_id)}) "
              "on conflict (id) do update set name = excluded.name;",
          )

      for tenant_id, group_key in groups:
          write_statement(
              handle,
              "insert into public.groups (tenant_id, group_key, name) "
              f"values ({sql_text(tenant_id)}, {sql_text(group_key)}, {sql_text(group_key)}) "
              "on conflict (tenant_id, group_key) do update set name = excluded.name;",
          )

      for user in users:
          write_statement(
              handle,
              "insert into public.users (user_id, tenant_id, display_name, department, is_admin) "
              f"values ({sql_text(user['user_id'])}, {sql_text(user['tenant_id'])}, "
              f"{sql_text(user['user_id'])}, {sql_text(user['department'])}, {sql_bool(user.get('is_admin', False))}) "
              "on conflict (user_id) do update set "
              "tenant_id = excluded.tenant_id, display_name = excluded.display_name, "
              "department = excluded.department, is_admin = excluded.is_admin;",
          )
          for group in user.get("groups", []):
              write_statement(
                  handle,
                  "insert into public.user_groups (user_id, group_id) "
                  f"select {sql_text(user['user_id'])}, id from public.groups "
                  f"where tenant_id = {sql_text(user['tenant_id'])} and group_key = {sql_text(group)} "
                  "on conflict do nothing;",
              )
          for project_id in user.get("project_ids", []):
              write_statement(
                  handle,
                  "insert into public.user_projects (user_id, tenant_id, project_id) "
                  f"values ({sql_text(user['user_id'])}, {sql_text(user['tenant_id'])}, {sql_text(project_id)}) "
                  "on conflict do nothing;",
              )

      for document in documents.values():
          write_statement(
              handle,
              "insert into public.documents "
              "(document_id, tenant_id, title, department, project_id, document_type, document_version, updated_at) "
              f"values ({sql_text(document['document_id'])}, {sql_text(document['tenant_id'])}, "
              f"{sql_text(document['title'])}, {sql_text(document['department'])}, "
              f"{sql_text(document['project_id'])}, {sql_text(document['document_type'])}, "
              f"{sql_int(document.get('document_version'))}, {sql_timestamptz(document.get('updated_at'))}) "
              "on conflict (document_id) do update set "
              "tenant_id = excluded.tenant_id, title = excluded.title, department = excluded.department, "
              "project_id = excluded.project_id, document_type = excluded.document_type, "
              "document_version = excluded.document_version, updated_at = excluded.updated_at;",
          )

      for chunk in chunks:
          content = chunk.get("content") or chunk.get("text") or ""
          write_statement(
              handle,
              "insert into public.chunks "
              "(chunk_id, document_id, content, content_hash, embedding_model_version, updated_at) "
              f"values ({sql_text(chunk['chunk_id'])}, {sql_text(chunk['document_id'])}, "
              f"{sql_text(content)}, {sql_text(chunk.get('content_hash'))}, "
              f"{sql_text(chunk.get('embedding_model_version'))}, {sql_timestamptz(chunk.get('updated_at'))}) "
              "on conflict (chunk_id) do update set "
              "document_id = excluded.document_id, content = excluded.content, "
              "content_hash = excluded.content_hash, embedding_model_version = excluded.embedding_model_version, "
              "updated_at = excluded.updated_at;",
          )

      for document_id, tenant_id, group_key in sorted(document_groups):
          write_statement(
              handle,
              "insert into public.document_acl_groups (document_id, group_id) "
              f"select {sql_text(document_id)}, id from public.groups "
              f"where tenant_id = {sql_text(tenant_id)} and group_key = {sql_text(group_key)} "
              "on conflict do nothing;",
          )

      write_statement(handle, "commit;")
      write_statement(handle, "")
      write_statement(handle, "-- Bind real Supabase Auth users manually, for example:")
      write_statement(
          handle,
          "-- insert into public.auth_user_acl_profiles (auth_user_id, acl_user_id) "
          "select id, 'backend-user-01' from auth.users where email = 'demo@example.com';",
      )
    finally:
        if output:
            output.close()


if __name__ == "__main__":
    main()
